"""add jsonb payloads to encounters table

Revision ID: 962f92a09320
Revises: c3d4e5f6a7b8
Create Date: 2026-06-11 11:33:18.145135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '962f92a09320'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('metabolic_panel_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('encounters', sa.Column('clinical_history_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('encounters', sa.Column('adherence_self_report', sa.String(length=20), nullable=True))
    op.create_index('ix_encounters_metabolic_panel_payload_gin', 'encounters', ['metabolic_panel_payload'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_encounters_metabolic_panel_payload_gin', table_name='encounters', postgresql_using='gin')
    op.drop_column('encounters', 'adherence_self_report')
    op.drop_column('encounters', 'clinical_history_payload')
    op.drop_column('encounters', 'metabolic_panel_payload')
    # ### end Alembic commands ###
