"""add_full_name_hash_to_patients

Revision ID: aa60cfa62c90
Revises: a1b2c3d4e5f6
Create Date: 2026-05-03 22:53:02.014765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa60cfa62c90'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'adjudication_logs', 'clinical_traceability', ['requirement_id'], ['id'])
    op.add_column('patients', sa.Column('full_name_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_patients_full_name_hash'), 'patients', ['full_name_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_full_name_hash'), table_name='patients')
    op.drop_column('patients', 'full_name_hash')
    op.drop_constraint(None, 'adjudication_logs', type_='foreignkey')
    # ### end Alembic commands ###
