"""add agreement_rate to encounter

Revision ID: c032f4bc73dc
Revises: c806a0d6c2f5
Create Date: 2026-03-29 10:57:59.232352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c032f4bc73dc'
down_revision: Union[str, Sequence[str], None] = 'c806a0d6c2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('agreement_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounters', 'agreement_rate')
    # ### end Alembic commands ###
