"""add_decision_audit_log

Revision ID: c806a0d6c2f5
Revises: 6df267294a99
Create Date: 2026-03-29 10:29:45.864790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c806a0d6c2f5'
down_revision: Union[str, Sequence[str], None] = '6df267294a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.String(length=255), nullable=False),
    sa.Column('engine_name', sa.String(length=100), nullable=False),
    sa.Column('engine_version_hash', sa.String(length=64), nullable=False),
    sa.Column('decision_type', sa.Enum('AGREEMENT', 'OVERRIDE', name='decisiontype'), nullable=False),
    sa.Column('reason_code', sa.Enum('AGREE_INSIGHT', 'OVERRIDE_CLINICAL_INTUITION', 'OVERRIDE_ECONOMIC_BARRIER', 'OVERRIDE_MISSING_CONTEXT', 'OVERRIDE_PATIENT_REFUSAL', name='reasoncode'), nullable=False),
    sa.Column('physician_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_audit_logs_encounter_id'), 'decision_audit_logs', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_decision_audit_logs_engine_name'), 'decision_audit_logs', ['engine_name'], unique=False)
    op.create_index(op.f('ix_decision_audit_logs_physician_id'), 'decision_audit_logs', ['physician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_audit_logs_physician_id'), table_name='decision_audit_logs')
    op.drop_index(op.f('ix_decision_audit_logs_engine_name'), table_name='decision_audit_logs')
    op.drop_index(op.f('ix_decision_audit_logs_encounter_id'), table_name='decision_audit_logs')
    op.drop_table('decision_audit_logs')
    # ### end Alembic commands ###
